# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  config.vm.network "private_network", ip: "192.168.0.20"
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF
    DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
    CODENAME=$(lsb_release -cs)
    
    echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
    
    sudo apt-get -y update

    # install mesos - this pulls in zookeeper
    sudo apt-get -y install mesos
    
    # disable zookeeper
    sudo service zookeeper stop
    sudo sh -c "echo manual > /etc/init/zookeeper.override"

    # set zookeeper config to master node
    sudo sh -c "echo zk://192.168.0.10:2181/mesos > /etc/mesos/zk"

    # disable mesos master
    sudo service mesos-master stop
    sudo sh -c "echo manual > /etc/init/mesos-master.override"

    # set ip address flag used when running mesos slave
    sudo sh -c "echo IP=192.168.0.20 >> /etc/default/mesos-slave"

    # enable docker support
    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    sudo sh -c "echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list"

    sudo apt-get -y update

    sudo apt-get -y install linux-image-extra-$(uname -r)
    sudo apt-get -y install docker-engine
    sudo service docker restart

    sudo sh -c "echo 'docker,mesos' > /etc/mesos-slave/containerizers"
    sudo sh -c "echo '5mins' > /etc/mesos-slave/executor_registration_timeout"

    sudo service mesos-slave restart
  SHELL
end
