# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  config.vm.network "private_network", ip: "192.168.50.10"
  
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     # vb.gui = true
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end
  

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF
    DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
    CODENAME=$(lsb_release -cs)
    
    echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
    
    sudo apt-get -y update

    # install mesos - this pulls in zookeeper
    sudo apt-get -y install mesos

    sudo su -c "echo 5 > /etc/zookeeper/conf/myid"

    sudo cp /vagrant/zoo.cfg /etc/zookeeper/conf/zoo.cfg

    sudo service zookeeper restart

    sudo su -c "echo zk://192.168.50.10:2181/mesos > /etc/mesos/zk"

    sudo service mesos-master restart

  SHELL
end
